.TH "dlb" 1 "Fri Aug 16 2024" "Version 3.4.1" "Dynamic Load Balance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlb \- DLB utility command\&. 

.SH "SYNOPSIS"
.PP
\fBdlb\fP {--affinity | --help [--help] | --version} 
.SH "DESCRIPTION"
.PP
Utility command to display all DLB options, print DLB version, or check process affinity\&.
.PP
.IP "\fB-a, --affinity \fP" 1c
Print process affinity\&.
.PP
.IP "\fB-h, --help \fP" 1c
Print DLB variables and current value\&. Use the option twice (e\&.g\&., -hh) for extended info\&.
.PP
.IP "\fB-v, --version \fP" 1c
Print version info\&. 
.PP
.SH "AUTHOR"
.PP
Barcelona Supercomputing Center (dlb@bsc.es) 
.SH "SEE ALSO"
.PP
\fBdlb_run\fP(1), \fBdlb_shm\fP(1), \fBdlb_taskset\fP(1) 
