.TH "dlb_shm" 1 "Fri Aug 16 2024" "Version 3.4.1" "Dynamic Load Balance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlb_shm \- Manage DLB shared memory\&. 

.SH "SYNOPSIS"
.PP
\fBdlb_shm\fP {--list | --delete | --help} 
.SH "DESCRIPTION"
.PP
Utility command to list or delete the DLB shared memory\&.
.PP
.IP "\fB-l, --list \fP" 1c
Print the DLB shared memory data\&.
.PP
.IP "\fB-d, --delete \fP" 1c
Delete the DLB shared memory\&.
.PP
.IP "\fB-h, --help \fP" 1c
Print usage\&. 
.PP
.SH "AUTHOR"
.PP
Barcelona Supercomputing Center (dlb@bsc.es) 
.SH "SEE ALSO"
.PP
\fBdlb\fP(1), \fBdlb_run\fP(1), \fBdlb_taskset\fP(1) 
